baseURL = "https://blog.hadageto.com"
title = "Hadageto Blog"
theme = "zzo"

defaultContentLanguage="en"
defaultContentLanguageInSubdir = true
hasCJKLanguage = false

summaryLength = 70
buildFuture = false

copyright = "@{year}, All Rights Reserved"
timeout = 10000
enableEmoji = true
paginate = 10
rssLimit = 100

enableGitInfo = false
googleAnalytics = "UA-163088660-1"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

